Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*'
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
